package com.example.ngontol

object OpenerData {
    val partnerPatterns = listOf(
        "[Undangan]"
    )

    val cocokPatterns = listOf("[Cocok]Dia sangat cocok denganmu!")


    val genZOpeners = listOf(
        "random tapi vibes km lucu",
        "km tuh kayak bikin enak",
        "jangan gitu, gemeter aku",
        "km tuh bikin mikir kotor",
        "suara km pasti bikin zonk",
        "lagi bayangin kamu hehe",
        "aku penasaran sama kamu~",
        "jangan sok cool gitu napa",
        "km pasti jago manja ya?",
        "aku yakin km pinter mijet",
        "km tipe yg dominan ya?",
        "kalau peluk km diem ga?",
        "km bisa bikin aku diem",
        "abis mandi ya? keliatan~",
        "aku deg2an liat fotomu",
        "muka km tuh ngeres manis",
        "lagi pake baju apa tuh?",
        "ciuman kamu tipe kalem ya?",
        "aku sih nurut sama kamu~",
        "jangan bales ya, bahaya~",
        "km cocok dibikin nyaman",
        "aku pilih km loh..",
        "cuma kamu yg aku buka",
        "gak semua aku bales loh",
        "km tuh beda, sumpahhh",
        "km tuh nyakitin tapi enak",
        "aku tuh lemah liat senyum km",
        "liat kamu tuh kaya dosa manis",
        "jangan senyum gitu napaaa 😩",
        "km tuh fix bikin overthinking",
        "aku suka vibe badboy km",
        "chat km tuh bikin candu 😵‍💫",
        "pake filter apa sih? kok bikin penasaran",
        "aku tuh pengen deket terus",
        "km suka manja, aku suka ngeladeni",
        "aku ngga ngerti, tapi pengen 😳",
        "liat kamu, langsung pengen login hati",
        "km tuh bikin auto nunduk",
        "aku suka cara km diem tapi bahaya",
        "peluk virtual km kerasa nyata hehee",
        "km kayaknya suka dimanja ya?",
        "bales dikit aja, aku bahagia kok",
        "aku suka cara km bales chat",
        "km jahat, tapi lucu 😔",
        "aku tuh pengen deket, tapi takut jatuh"
    )


    val morningOpeners = listOf(
        "bangun yaa? aku kangenn",
        "abis mimpiin aku yaa? 😋",
        "udah sarapan blm sih?",
        "kok pagi2 inget kamu ya 😳",
        "km tuh ganggu pikiran bgt",
        "bangun langsung liat notif km",
        "pagi2 gini... rindu siapa?",
        "km kebayang pas buka mata",
        "aku bangun pengen nyapa km",
        "km tuh bikin pagi seger 😭",
        "sun pagi dulu dongg",
        "mimpiin siapa td malem??",
        "km suka pagi yg peluk?",
        "eh, udah bangun belom sih?",
        "km tim kopi atau peluk?",
        "km anaknya morning kiss ya?",
        "mau dipanggiil sayang pagi ini?",
        "km tuh mood booster aku 😌",
        "pagi2 gini, bales dong 😭",
        "km tuh sweet kaya sinar pagi",
        "mataharinya kalah manis sama kamu",
        "pagi-pagi gini... yang aku cari ya kamu",
        "kalau km sarapan, aku kenyang 😋",
        "bangun! aku udah nungguin balasan",
        "km bangunnya sambil senyum ya?",
        "pagi km tuh mood aku seharian",
        "udah liat cermin? cakep bgt kamu",
        "aku iri sama bantal km semalem",
        "km tuh cocoknya jadi alasan bangun",
        "pagi-pagi gini, peluk virtual dulu yuk",
        "aku udah senyum gara-gara notif kamu",
        "kopi boleh, tapi kamu manisnya beda",
        "km udah senyum blm pagi ini?",
        "aku pengen nyium jidat kamuu",
        "pagi km tuh aura-nya nyenengin"

    )
    val noonOpeners = listOf(
        "makan siang udah belom?",
        "abis ini peluk aku ya 😋",
        "bosen kerja? aku juga 😭",
        "jam segini enaknya ngapain?",
        "liat notif km bikin semangat",
        "ciuman siang gak papa kan?",
        "aku ngantuk, pelukin dongg",
        "km pasti jago pegang kepala",
        "kerja sambil mikirin aku ya?",
        "bales dong, aku gelisah 😢",
        "km keliatan produktif bgt..",
        "siang gini enaknya manja",
        "aku butuh perhatian skrg~",
        "gak ada chat km sepi bgt",
        "lagi diem sambil mikirin kamu",
        "kalau bareng km, jam cepet..",
        "aku bales yg waras aja 😘",
        "jangan cuekin aku dong 😔",
        "lagi ngantuk, curhat yuk?",
        "aku tuh pengen kamu skrg",
        "kerja semangat ya, aku nemenin~",
        "udah capek? sini aku pegang dikit",
        "liat km tuh bikin jam istirahat enakk",
        "kalau bareng km, waktu slow mo",
        "aku bosen tapi kamu seru 😭",
        "lagi ngantuk? aku ada nih buat nemenin",
        "km tuh kayak charger di jam 12",
        "bales dong, aku butuh vitamin km",
        "kalau siang gini, aku craving kamu",
        "aku tuh pengen ngemil kamu 😋",
        "km tuh cocok jadi pelarian jam kerja",
        "pengen deh curi waktu lunch bareng kamu",
        "lagi hectic? semangat, aku support km",
        "balesannya km tuh segerin otak",
        "km pasti cakep juga pas serius kerja"

    )
    val nightOpeners = listOf(
        "km tuh bikin malam rame",
        "abis ini peluk aku ya..",
        "km enak diajak ngobrol malem",
        "aku udah nungguin km loh",
        "malem gini sendirian ya?",
        "bales dong... sepi bgt 😢",
        "lagi rebahan mikirin km 😳",
        "kalau km dateng, aku tenang",
        "aku tuh pengen deket km",
        "km tipe peluk kenceng ya?",
        "malem gini enaknya dipelukkk",
        "bales ya, km bikin penasaran",
        "aku pengen cerita ke kamu",
        "jangan tidur dulu dong 😔",
        "km manisnya ngangenin sih",
        "aku butuh ditemenin malem ini",
        "km kebayang terus dari tadi",
        "chat km tuh mood booster",
        "aku suka suara malem kamu",
        "kalau boleh, aku peluk ya?",
        "malem tuh gak lengkap tanpa km",
        "aku diem tapi nunggu notif kamu",
        "km tuh bikin malem gak sendu",
        "abis ini call-an yuk, suara kamu calming",
        "lagi ngelamun apa, hayo?",
        "malem gini vibes kamu lebih terasa",
        "km manis banget kalo udah capek",
        "aku tuh cuma pengen deket km sekarang",
        "km bikin overthinking sampe susah tidur",
        "aku suka cara kamu hadir pelan-pelan",
        "chat kamu tuh bikin ketagihan",
        "km cocok jadi alasan aku gak tidur",
        "lagi rebahan, tapi pikiran ke kamu",
        "malem-malem gini, aku pengen kamu diem di sini aja",
        "km tuh kayak bintang, susah dijangkau tapi keliatan terus"


    )
    val lateNightOpeners = listOf(
        "lagi gak bisa tidur jg ya?",
        "aku pengen dengerin suara km",
        "pikiranku km semua skrg 😳",
        "peluk aku dulu boleh gak?",
        "malem makin aneh mikirin km",
        "aku ngetik sambil gemeter 😭",
        "aku diem2 pengen km sih",
        "jangan ganggu, aku ngebayangin",
        "km tuh bahaya jam seginii",
        "lagi ngelamunin siapa nih?",
        "kalau peluk, km diem aja ya?",
        "aku suka malem gini, sama km",
        "km jahat, bikin aku mikir 😔",
        "aku takut bales km terus 😳",
        "jangan bales ya, bahaya...",
        "aku udah ngebayangin km sih",
        "kalau telepon, mau denger gak?",
        "lagi tidur? aku liatin aja yaa",
        "km tuh kelewat bikin tenang",
        "aku ngelamunin km dari tadi",
        "aku tuh suka km versi jam 1 pagi",
        "lagi scroll sambil mikirin kamu 😶",
        "suara hati aku tuh nyebut kamu terus",
        "kalau call-an, kamu diem aja ya?",
        "aku tuh capek mikirin km, tapi nagih",
        "lagi diem tapi pikiran ke km",
        "km tuh kelewat enak buat dibayangin 😳",
        "malem makin dalem, pikiranku makin liar",
        "lagi ngetik tapi sambil nahan rindu",
        "aku takut bales, nanti makin sayang",
        "km muncul terus di kepala",
        "kalau peluk sekarang, kamu diem ya?",
        "aku suka suasana malem bareng kamu",
        "tutup mata tapi bayangin km",
        "km tuh bikin ngantuknya ilang"
    )
    val delayMessages = listOf(
        "Bentar ya, lagi ada urusan sebentar",
        "Lagi ambil minum bentar",
        "Sabar ya, lagi ada telepon",
        "Tahan dulu, lagi ngerapihin barang",
        "Lagi keluar kamar bentar",
        "Bentar, ada yang manggil",
        "Lagi ngecek sesuatu dulu",
        "Sabar ya, lagi ke toilet",
        "Lagi siapin makanan sebentar",
        "Bentar ya, lagi ambil charger",
        "Lagi ganti posisi duduk",
        "Sebentar, lagi liat notif lain",
        "Lagi matiin TV sebentar",
        "Bentar ya, lagi nyari kunci",
        "Lagi beresin meja bentar",
        "Sabar ya, lagi nutup pintu",
        "Bentar, lagi ngerapiin tempat tidur",
        "Lagi nyalain lampu dulu",
        "Sebentar, lagi ngecek pintu",
        "Lagi siapin buku/alat tulis bentar",
        "Bentar, ada chat lain masuk",
        "Sabar ya, lagi baca ulang",
        "Lagi ngecek sinyal sebentar",
        "Bentar, lagi matiin kipas",
        "Lagi mindahin file bentar",
        "Bentar ya, lagi balas pesan lain",
        "Sabar ya, lagi ngecek jam",
        "Lagi ngerapiin headset sebentar",
        "Bentar, lagi ngecek tas",
        "Lagi cuci tangan bentar",
        "Sebentar ya, ada notif kerjaan",
        "Bentar, lagi ngecek kalender",
        "Lagi mindahin kursi dulu",
        "Sabar ya, lagi ngecek cuaca",
        "Bentar, lagi save dokumen",
        "Lagi update aplikasi bentar",
        "Sebentar, lagi restart HP",
        "Bentar ya, lagi baca info penting",
        "Lagi masukkin barang ke tas bentar",
        "Bentar, lagi cek email",
        "Lagi nyari remote bentar",
        "Bentar, lagi rapihin kabel",
        "Lagi siapin charger sebentar",
        "Sebentar ya, ada pesan kerjaan",
        "Bentar, lagi mindahin barang",
        "Lagi cek paket bentar",
        "Bentar ya, lagi matiin suara",
        "Lagi buka laptop dulu",
        "Bentar, lagi save progress",
        "Sabar ya, lagi ngecek dokumen",
        "Bentar, lagi setting HP",
        "Lagi rapihin kursi bentar",
        "Bentar ya, lagi buka pintu",
        "Lagi ambil cemilan sebentar",
        "Bentar, lagi cek koneksi",
        "Sabar ya, lagi ngecek jadwal",
        "Bentar ya, lagi matiin aplikasi",
        "Lagi nyari charger laptop",
        "Bentar, lagi rapihin tas",
        "Lagi siapin headset bentar",
        "Sebentar ya, lagi save file",
        "Bentar, lagi cek baterai",
        "Lagi rapihin bantal sebentar",
        "Bentar ya, lagi ambil catatan",
        "Lagi cek kalender kerjaan",
        "Sebentar, lagi update sistem",
        "Bentar, lagi cek kuota",
        "Lagi mindahin data sebentar",
        "Bentar ya, lagi sinkronisasi",
        "Sabar ya, lagi ngerapiin kamar",
        "Bentar, lagi cek aplikasi",
        "Lagi rapihin dokumen sebentar",
        "Bentar ya, lagi install update",
        "Lagi cek notifikasi email",
        "Sebentar, lagi isi air minum",
        "Bentar, lagi buka jendela",
        "Lagi siapin laptop sebentar",
        "Bentar ya, lagi ngecek kabel",
        "Sabar ya, lagi restart laptop",
        "Bentar, lagi rapihin meja kerja",
        "Lagi cek jadwal meeting",
        "Bentar ya, lagi ngecas HP",
        "Sebentar, lagi print dokumen",
        "Bentar, lagi isi baterai laptop",
        "Lagi siapin alat tulis sebentar",
        "Bentar ya, lagi cek notifikasi",
        "Lagi matiin lampu bentar",
        "Bentar, lagi cek folder",
        "Sabar ya, lagi ngerapiin file",
        "Bentar, lagi ambil tisu",
        "Lagi siapin kopi sebentar",
        "Bentar ya, lagi cek suara",
        "Lagi mindahin data ke cloud",
        "Sebentar ya, lagi ambil jaket",
        "Bentar, lagi cek koneksi WiFi",
        "Lagi siapin makan siang",
        "Bentar ya, lagi update data",
        "Sabar ya, lagi rapihin catatan",
        "Bentar, lagi ambil sesuatu",
        "Lagi cek baterai HP bentar",
        "Bentar ya, lagi balas email",
        "Sebentar, lagi matiin alarm",
        "Bentar, lagi cek browser",
        "Lagi siapin barang bentar",
        "Bentar ya, lagi save catatan"
    )
}
