package com.example.ngontol

object OpenerData {
    val partnerPatterns = listOf(
        "[Undangan]"
    )

    val cocokPatterns = listOf("[Cocok]Dia sangat cocok denganmu!")


    val genZOpeners = listOf(
        "random tapi vibes km lucu",
        "km tuh kayak bikin enak",
        "jangan gitu, gemeter aku",
        "km tuh bikin mikir kotor",
        "suara km pasti bikin zonk",
        "lagi bayangin kamu hehe",
        "aku penasaran sama kamu~",
        "jangan sok cool gitu napa",
        "km pasti jago manja ya?",
        "aku yakin km pinter mijet",
        "km tipe yg dominan ya?",
        "kalau peluk km diem ga?",
        "km bisa bikin aku diem",
        "abis mandi ya? keliatan~",
        "aku deg2an liat fotomu",
        "muka km tuh ngeres manis",
        "lagi pake baju apa tuh?",
        "ciuman kamu tipe kalem ya?",
        "aku sih nurut sama kamu~",
        "jangan bales ya, bahaya~",
        "km cocok dibikin nyaman",
        "aku pilih km loh..",
        "cuma kamu yg aku buka",
        "gak semua aku bales loh",
        "km tuh beda, sumpahhh",
        "km tuh nyakitin tapi enak",
        "aku tuh lemah liat senyum km",
        "liat kamu tuh kaya dosa manis",
        "jangan senyum gitu napaaa 😩",
        "km tuh fix bikin overthinking",
        "aku suka vibe badboy km",
        "chat km tuh bikin candu 😵‍💫",
        "pake filter apa sih? kok bikin penasaran",
        "aku tuh pengen deket terus",
        "km suka manja, aku suka ngeladeni",
        "aku ngga ngerti, tapi pengen 😳",
        "liat kamu, langsung pengen login hati",
        "km tuh bikin auto nunduk",
        "aku suka cara km diem tapi bahaya",
        "peluk virtual km kerasa nyata hehee",
        "km kayaknya suka dimanja ya?",
        "bales dikit aja, aku bahagia kok",
        "aku suka cara km bales chat",
        "km jahat, tapi lucu 😔",
        "aku tuh pengen deket, tapi takut jatuh"
    )


    val morningOpeners = listOf(
        "bangun yaa? aku kangenn",
        "abis mimpiin aku yaa? 😋",
        "udah sarapan blm sih?",
        "kok pagi2 inget kamu ya 😳",
        "km tuh ganggu pikiran bgt",
        "bangun langsung liat notif km",
        "pagi2 gini... rindu siapa?",
        "km kebayang pas buka mata",
        "aku bangun pengen nyapa km",
        "km tuh bikin pagi seger 😭",
        "sun pagi dulu dongg",
        "mimpiin siapa td malem??",
        "km suka pagi yg peluk?",
        "eh, udah bangun belom sih?",
        "km tim kopi atau peluk?",
        "km anaknya morning kiss ya?",
        "mau dipanggiil sayang pagi ini?",
        "km tuh mood booster aku 😌",
        "pagi2 gini, bales dong 😭",
        "km tuh sweet kaya sinar pagi",
        "mataharinya kalah manis sama kamu",
        "pagi-pagi gini... yang aku cari ya kamu",
        "kalau km sarapan, aku kenyang 😋",
        "bangun! aku udah nungguin balasan",
        "km bangunnya sambil senyum ya?",
        "pagi km tuh mood aku seharian",
        "udah liat cermin? cakep bgt kamu",
        "aku iri sama bantal km semalem",
        "km tuh cocoknya jadi alasan bangun",
        "pagi-pagi gini, peluk virtual dulu yuk",
        "aku udah senyum gara-gara notif kamu",
        "kopi boleh, tapi kamu manisnya beda",
        "km udah senyum blm pagi ini?",
        "aku pengen nyium jidat kamuu",
        "pagi km tuh aura-nya nyenengin"

    )
    val noonOpeners = listOf(
        "makan siang udah belom?",
        "abis ini peluk aku ya 😋",
        "bosen kerja? aku juga 😭",
        "jam segini enaknya ngapain?",
        "liat notif km bikin semangat",
        "ciuman siang gak papa kan?",
        "aku ngantuk, pelukin dongg",
        "km pasti jago pegang kepala",
        "kerja sambil mikirin aku ya?",
        "bales dong, aku gelisah 😢",
        "km keliatan produktif bgt..",
        "siang gini enaknya manja",
        "aku butuh perhatian skrg~",
        "gak ada chat km sepi bgt",
        "lagi diem sambil mikirin kamu",
        "kalau bareng km, jam cepet..",
        "aku bales yg waras aja 😘",
        "jangan cuekin aku dong 😔",
        "lagi ngantuk, curhat yuk?",
        "aku tuh pengen kamu skrg",
        "kerja semangat ya, aku nemenin~",
        "udah capek? sini aku pegang dikit",
        "liat km tuh bikin jam istirahat enakk",
        "kalau bareng km, waktu slow mo",
        "aku bosen tapi kamu seru 😭",
        "lagi ngantuk? aku ada nih buat nemenin",
        "km tuh kayak charger di jam 12",
        "bales dong, aku butuh vitamin km",
        "kalau siang gini, aku craving kamu",
        "aku tuh pengen ngemil kamu 😋",
        "km tuh cocok jadi pelarian jam kerja",
        "pengen deh curi waktu lunch bareng kamu",
        "lagi hectic? semangat, aku support km",
        "balesannya km tuh segerin otak",
        "km pasti cakep juga pas serius kerja"

    )
    val nightOpeners = listOf(
        "km tuh bikin malam rame",
        "abis ini peluk aku ya..",
        "km enak diajak ngobrol malem",
        "aku udah nungguin km loh",
        "malem gini sendirian ya?",
        "bales dong... sepi bgt 😢",
        "lagi rebahan mikirin km 😳",
        "kalau km dateng, aku tenang",
        "aku tuh pengen deket km",
        "km tipe peluk kenceng ya?",
        "malem gini enaknya dipelukkk",
        "bales ya, km bikin penasaran",
        "aku pengen cerita ke kamu",
        "jangan tidur dulu dong 😔",
        "km manisnya ngangenin sih",
        "aku butuh ditemenin malem ini",
        "km kebayang terus dari tadi",
        "chat km tuh mood booster",
        "aku suka suara malem kamu",
        "kalau boleh, aku peluk ya?",
        "malem tuh gak lengkap tanpa km",
        "aku diem tapi nunggu notif kamu",
        "km tuh bikin malem gak sendu",
        "abis ini call-an yuk, suara kamu calming",
        "lagi ngelamun apa, hayo?",
        "malem gini vibes kamu lebih terasa",
        "km manis banget kalo udah capek",
        "aku tuh cuma pengen deket km sekarang",
        "km bikin overthinking sampe susah tidur",
        "aku suka cara kamu hadir pelan-pelan",
        "chat kamu tuh bikin ketagihan",
        "km cocok jadi alasan aku gak tidur",
        "lagi rebahan, tapi pikiran ke kamu",
        "malem-malem gini, aku pengen kamu diem di sini aja",
        "km tuh kayak bintang, susah dijangkau tapi keliatan terus"


    )
    val lateNightOpeners = listOf(
        "lagi gak bisa tidur jg ya?",
        "aku pengen dengerin suara km",
        "pikiranku km semua skrg 😳",
        "peluk aku dulu boleh gak?",
        "malem makin aneh mikirin km",
        "aku ngetik sambil gemeter 😭",
        "aku diem2 pengen km sih",
        "jangan ganggu, aku ngebayangin",
        "km tuh bahaya jam seginii",
        "lagi ngelamunin siapa nih?",
        "kalau peluk, km diem aja ya?",
        "aku suka malem gini, sama km",
        "km jahat, bikin aku mikir 😔",
        "aku takut bales km terus 😳",
        "jangan bales ya, bahaya...",
        "aku udah ngebayangin km sih",
        "kalau telepon, mau denger gak?",
        "lagi tidur? aku liatin aja yaa",
        "km tuh kelewat bikin tenang",
        "aku ngelamunin km dari tadi",
        "aku tuh suka km versi jam 1 pagi",
        "lagi scroll sambil mikirin kamu 😶",
        "suara hati aku tuh nyebut kamu terus",
        "kalau call-an, kamu diem aja ya?",
        "aku tuh capek mikirin km, tapi nagih",
        "lagi diem tapi pikiran ke km",
        "km tuh kelewat enak buat dibayangin 😳",
        "malem makin dalem, pikiranku makin liar",
        "lagi ngetik tapi sambil nahan rindu",
        "aku takut bales, nanti makin sayang",
        "km muncul terus di kepala",
        "kalau peluk sekarang, kamu diem ya?",
        "aku suka suasana malem bareng kamu",
        "tutup mata tapi bayangin km",
        "km tuh bikin ngantuknya ilang"

    )

    val delayMessages = listOf(
        "Btr ya beb lg pipis",
        "Lagi minum bentar ya",
        "Sabar ya lg sikat",
        "Btr beb, lg nyeduh",
        "Lagi susah sinyal nih wkwk",
        "Antriin mamah dulu",
        "Matiin lampu dlu ya",
        "Lagi cari headset",
        "Btr ya, lg ngelap",
        "Lagi cuci muka nih beb..",
        "Lagi ngelap pipi",
        "Btr beb, ngaca dulu",
        "Masih ketawa ini",
        "Ke kamar mandi dlu",
        "Lagi makan bentar ya",
        "Btr yaa, ada adik akuu",
        "Lagi buka jendela",
        "Btr beb ambil minum hehee",
        "Sabar yaa, ngupil",
        "ada kucing lucu 😭",
        "Btr ya, nyium kucing",
        "Ngoles minyak dlu",
        "Btr ya, lg maskeran",
        "Kepencet tisu nih",
        "Lagi ngelap keyboard",
        "Btr yaa lg nyeruput",
        "Lagi ngunyah wkwk",
        "Lagi semedi bentar",
        "Ngopi dulu beb ☕",
        "Btr yaa, lg minum",
        "Mau bersin nih 😤",
        "Tahan ketawa dlu",
        "Lagi curhat ke kamu",
        "Baru nyadar typo 😵",
        "Btr beb lg mikir",
        "Lagi ngetik ulang",
        "Btr beb lg stalking",
        "Lagi liatin chat atas",
        "Lagi nahan kentut 😭",
        "Ngumpulin nyawa dlu",
        "Mau ganti baju dulu",
        "Btr ya, sinyal ngaco",
        "Ke WC, sabar yaaa",
        "Lagi ngelirik kamu",
        "Masih bengong dikit",
        "Sambil nyanyi bentar",
        "Ketawa dulu barusan",
        "Btr beb lg mode slow",
        "Baru buka mata nih",
        "Lagi ngecas HP"
    )

}
