name: Reset sentToday

on:
  schedule:
    # reset tiap jam 00:00 WIB (WIB = UTC+7)
    - cron: "11 14 * * *"   # 17 UTC = 00 WIB
  workflow_dispatch:       # biar bisa lo jalankan manual dari GitHub Actions tab

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Run reset script
        run: node scripts/resetSentToday.js
