name: Reset sentToday

on:
  schedule:
    - cron: "44 13 * * *" # jalan tiap hari jam 20:35 WIB
  workflow_dispatch: # bisa manual juga

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install firebase-admin

      - name: Reset sentToday
        env:
          FIREBASE_SA_B64: ${{ secrets.FIREBASE_SA_B64 }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
        run: |
          echo "$FIREBASE_SA_B64" | base64 --decode > sa.json
          node <<'EOF'
          const admin = require("firebase-admin");
          const fs = require("fs");

          const serviceAccount = JSON.parse(fs.readFileSync("sa.json", "utf8"));

          admin.initializeApp({
            credential: admin.credential.cert(serviceAccount),
            databaseURL: process.env.FIREBASE_DB_URL,
          });

          const db = admin.database();
          db.ref("devices").once("value").then(snap => {
            snap.forEach(child => {
              child.ref.child("sentToday").set(0);
            });
            console.log("✅ Reset selesai");
            process.exit(0);
          }).catch(err => {
            console.error("❌ Error:", err);
            process.exit(1);
          });
          EOF
