name: Reset disabled API keys

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install deps
        run: npm install firebase-admin
        
      - name: Create service account file
        run: echo "$FIREBASE_SA_B64" | base64 --decode | tr -d '\r' > sa.json
        env:
          FIREBASE_SA_B64: ${{ secrets.FIREBASE_SA_B64 }}

      - name: Run reset disabled
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
        run: node scripts/resetDisabled.js
