name: Reset sentToday

on:
  schedule:
    - cron: "25 14 * * *" # jam 00:00 WIB (17:00 UTC)
  workflow_dispatch: # bisa manual trigger juga

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install firebase-admin

      - name: Run reset script
        env:
          FIREBASE_SA_B64: ${{ secrets.FIREBASE_SA_B64 }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
        run: |
          node scripts/resetSentToday.js
